export * from './cep.pipe';
export * from './cpf.pipe';
export * from './firstWord.pipe';
export * from './formatBytes.pipe';
export * from './pis.pipe';
export * from './singular-plural.pipe';
export * from './time.pipe';
export * from './timeFormatter.pipe';
export * from './dayOfWeek.pipe';
export * from './monthName.pipe';
export * from './relativeTime.pipe'
export * from './customDate.pipe'
export * from './dash-if-empty.pipe'
